version: "3.7"

services: 
  database_ignite: 
    image: postgres
    container_name: database_ignite
    restart: always
    ports: 
      - 5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rentx
    volumes: 
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentx
    ports:
      - 3334:3334
    volumes: 
      - .:/usr/app
      - /usr/src/app/node_modules
    links:
      - database_ignite
    depends_on: 
      - database_ignite


volumes: 
  pgdata: 
    driver: local